// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//   Generated using OBeautifulCode.CodeGen.ModelObject (1.0.121.0)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Naos.Mongo.Domain.Test
{
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Collections.Concurrent;
    using global::System.Collections.Generic;
    using global::System.Collections.ObjectModel;
    using global::System.Diagnostics.CodeAnalysis;

    using global::FakeItEasy;

    using global::OBeautifulCode.AutoFakeItEasy;
    using global::OBeautifulCode.Math.Recipes;

    /// <summary>
    /// The default (code generated) Dummy Factory.
    /// Derive from this class to add any overriding or custom registrations.
    /// </summary>
    [ExcludeFromCodeCoverage]
    [GeneratedCode("OBeautifulCode.CodeGen.ModelObject", "1.0.121.0")]
#if !NaosMongoSolution
    internal
#else
    public
#endif
    abstract class DefaultMongoDummyFactory : IDummyFactory
    {
        public DefaultMongoDummyFactory()
        {
            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new MongoConnectionDefinition
                             {
                                 Server                     = A.Dummy<string>(),
                                 DatabaseName               = A.Dummy<string>(),
                                 UserName                   = A.Dummy<string>(),
                                 Password                   = A.Dummy<string>(),
                                 AuthenticationDatabaseName = A.Dummy<string>(),
                             });
        }

        /// <inheritdoc />
        public Priority Priority => new FakeItEasy.Priority(1);

        /// <inheritdoc />
        public bool CanCreate(Type type)
        {
            return false;
        }

        /// <inheritdoc />
        public object Create(Type type)
        {
            return null;
        }
    }
}